require('dotenv').config();
const mongoose=require('mongoose');
const Plant=require('../models/Plant');

const plants=[
  {
    "name": "Snake Plant",
    "price": 850,
    "category": "Indoor",
    "description": "A hardy, upright houseplant with sword-shaped leaves. It tolerates low light and infrequent watering, making it excellent for bedrooms, offices and apartments.",
    "image": "https://images.pexels.com/photos/4185555/pexels-photo-4185555.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Low to bright indirect",
    "water": "Every 1–2 weeks",
    "difficulty": "Easy",
    "height": "2–4 ft",
    "bestFor": "Indoor spaces",
    "temperature": "18–30°C",
    "petSafety": "Generally pet-toxic if chewed"
  },
  {
    "name": "Monstera Deliciosa",
    "price": 1200,
    "category": "Indoor",
    "description": "A tropical houseplant with large split leaves that creates a bold, lush look in living rooms and workspaces.",
    "image": "https://images.pexels.com/photos/32293880/pexels-photo-32293880.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect",
    "water": "About weekly",
    "difficulty": "Easy",
    "height": "3–8 ft indoors",
    "bestFor": "Living room / office",
    "temperature": "18–30°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "ZZ Plant",
    "price": 900,
    "category": "Indoor",
    "description": "A glossy, low-maintenance plant that stores water in its rhizomes and handles lower-light rooms very well.",
    "image": "https://images.pexels.com/photos/8166779/pexels-photo-8166779.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Low to bright indirect",
    "water": "Every 2–3 weeks",
    "difficulty": "Very easy",
    "height": "2–4 ft",
    "bestFor": "Bedroom / office",
    "temperature": "18–30°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Peace Lily",
    "price": 950,
    "category": "Indoor",
    "description": "An elegant leafy plant with white blooms. Keep its soil lightly moist and provide filtered light for steady growth.",
    "image": "https://images.pexels.com/photos/21656893/pexels-photo-21656893.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Medium to bright indirect",
    "water": "1–2 times weekly",
    "difficulty": "Medium",
    "height": "1–3 ft",
    "bestFor": "Bedroom / living room",
    "temperature": "18–30°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Rubber Plant",
    "price": 1100,
    "category": "Indoor",
    "description": "A decorative plant with thick, glossy leaves. Give it bright filtered light and avoid constantly wet soil.",
    "image": "https://images.pexels.com/photos/993018/pexels-photo-993018.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect",
    "water": "Every 1–2 weeks",
    "difficulty": "Easy",
    "height": "3–8 ft indoors",
    "bestFor": "Living room",
    "temperature": "18–30°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Spider Plant",
    "price": 700,
    "category": "Indoor",
    "description": "A fast-growing plant with arching striped leaves and baby plantlets. It is forgiving and easy for beginners.",
    "image": "https://images.pexels.com/photos/3854747/pexels-photo-3854747.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect to medium",
    "water": "Weekly",
    "difficulty": "Easy",
    "height": "1–2 ft",
    "bestFor": "Bedroom / office",
    "temperature": "15–30°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Calathea Orbifolia",
    "price": 1350,
    "category": "Indoor",
    "description": "A striking foliage plant with broad, silver-striped leaves. It prefers humidity, warmth and gentle indirect light.",
    "image": "https://images.pexels.com/photos/5091828/pexels-photo-5091828.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect",
    "water": "1–2 times weekly",
    "difficulty": "Medium",
    "height": "2–3 ft",
    "bestFor": "Bright indoor room",
    "temperature": "18–28°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Chinese Evergreen",
    "price": 800,
    "category": "Indoor",
    "description": "A durable foliage plant available in attractive green and patterned varieties. It adapts to many indoor conditions.",
    "image": "https://images.pexels.com/photos/9311882/pexels-photo-9311882.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Low to medium indirect",
    "water": "Every 1–2 weeks",
    "difficulty": "Easy",
    "height": "1–3 ft",
    "bestFor": "Office / bedroom",
    "temperature": "18–30°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Boston Fern",
    "price": 750,
    "category": "Indoor",
    "description": "A lush fern with soft, arching fronds. It grows best with humidity, indirect light and evenly moist soil.",
    "image": "https://images.pexels.com/photos/322342/pexels-photo-322342.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect",
    "water": "2–3 times weekly",
    "difficulty": "Medium",
    "height": "1–3 ft",
    "bestFor": "Bathroom / shaded room",
    "temperature": "18–28°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Fiddle Leaf Fig",
    "price": 1500,
    "category": "Indoor",
    "description": "A statement plant with large violin-shaped leaves. Give it bright indirect light and avoid frequent location changes.",
    "image": "https://images.pexels.com/photos/8857324/pexels-photo-8857324.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect",
    "water": "Every 1–2 weeks",
    "difficulty": "Medium",
    "height": "4–8 ft indoors",
    "bestFor": "Living room",
    "temperature": "18–30°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Areca Palm",
    "price": 1100,
    "category": "Outdoor",
    "description": "A tropical clumping palm that brings a resort-like feel to bright balconies, patios and sheltered outdoor areas.",
    "image": "https://images.pexels.com/photos/5538833/pexels-photo-5538833.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright filtered / partial sun",
    "water": "2–3 times weekly",
    "difficulty": "Medium",
    "height": "5–8 ft",
    "bestFor": "Balcony / patio",
    "temperature": "20–32°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Bougainvillea",
    "price": 1250,
    "category": "Outdoor",
    "description": "A vigorous flowering climber known for colorful bracts. It needs strong sunlight and excellent drainage.",
    "image": "https://images.pexels.com/photos/17317797/pexels-photo-17317797.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Full sun",
    "water": "2–3 times weekly",
    "difficulty": "Medium",
    "height": "4–12+ ft",
    "bestFor": "Balcony / garden",
    "temperature": "20–35°C",
    "petSafety": "Thorns; keep away from pets/children"
  },
  {
    "name": "Croton",
    "price": 900,
    "category": "Outdoor",
    "description": "A colorful foliage plant with yellow, orange, red and green leaves. Strong light helps maintain its colors.",
    "image": "https://images.pexels.com/photos/4503276/pexels-photo-4503276.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright light / partial sun",
    "water": "2 times weekly",
    "difficulty": "Medium",
    "height": "2–5 ft",
    "bestFor": "Balcony / patio",
    "temperature": "20–32°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Hibiscus",
    "price": 850,
    "category": "Outdoor",
    "description": "A tropical flowering plant that can produce large colorful blooms when given plenty of sunlight and regular feeding.",
    "image": "https://images.pexels.com/photos/17294447/pexels-photo-17294447.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Full sun",
    "water": "Daily to every 2 days in hot weather",
    "difficulty": "Medium",
    "height": "3–6 ft",
    "bestFor": "Balcony / garden",
    "temperature": "20–35°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Jade Plant",
    "price": 950,
    "category": "Outdoor",
    "description": "A compact succulent with thick leaves and woody stems. It likes strong light and very well-drained soil.",
    "image": "https://images.pexels.com/photos/5781634/pexels-photo-5781634.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright light / morning sun",
    "water": "Every 2–3 weeks",
    "difficulty": "Easy",
    "height": "1–3 ft",
    "bestFor": "Sunny balcony",
    "temperature": "18–30°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Dracaena Marginata",
    "price": 1000,
    "category": "Outdoor",
    "description": "A palm-like ornamental plant with narrow leaves and slender stems. It suits bright, sheltered areas and containers.",
    "image": "https://images.pexels.com/photos/4503822/pexels-photo-4503822.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect / filtered",
    "water": "Every 1–2 weeks",
    "difficulty": "Easy",
    "height": "3–6 ft",
    "bestFor": "Covered balcony",
    "temperature": "18–32°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Ixora",
    "price": 950,
    "category": "Outdoor",
    "description": "A compact tropical shrub with clusters of small flowers. It performs best in warm weather and bright light.",
    "image": "https://images.pexels.com/photos/32767496/pexels-photo-32767496.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Full sun to partial shade",
    "water": "2–3 times weekly",
    "difficulty": "Medium",
    "height": "2–5 ft",
    "bestFor": "Garden / balcony",
    "temperature": "20–35°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Plumeria",
    "price": 1300,
    "category": "Outdoor",
    "description": "A tropical flowering plant famous for fragrant blooms. Give it strong sunlight and a fast-draining growing medium.",
    "image": "https://images.pexels.com/photos/24419880/pexels-photo-24419880.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Full sun",
    "water": "2–3 times weekly",
    "difficulty": "Medium",
    "height": "5–15 ft",
    "bestFor": "Garden / sunny balcony",
    "temperature": "20–35°C",
    "petSafety": "Sap may irritate; keep away from pets"
  },
  {
    "name": "Bird of Paradise",
    "price": 1800,
    "category": "Outdoor",
    "description": "A dramatic tropical plant with large paddle-shaped leaves. It needs bright light, warmth and room to grow.",
    "image": "https://images.pexels.com/photos/10975125/pexels-photo-10975125.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright sun / bright indirect",
    "water": "1–2 times weekly",
    "difficulty": "Medium",
    "height": "4–8+ ft",
    "bestFor": "Patio / large balcony",
    "temperature": "18–32°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Gardenia",
    "price": 1200,
    "category": "Outdoor",
    "description": "A fragrant flowering shrub with glossy leaves. It prefers bright light, humidity and slightly acidic, well-drained soil.",
    "image": "https://images.pexels.com/photos/33072116/pexels-photo-33072116.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect to morning sun",
    "water": "2–3 times weekly",
    "difficulty": "Advanced",
    "height": "2–5 ft",
    "bestFor": "Balcony / garden",
    "temperature": "18–30°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Aloe Vera",
    "price": 650,
    "category": "Succulent",
    "description": "A practical succulent with thick water-storing leaves. Let the soil dry fully before watering again.",
    "image": "https://images.pexels.com/photos/7663180/pexels-photo-7663180.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright light",
    "water": "Every 2–3 weeks",
    "difficulty": "Very easy",
    "height": "1–2 ft",
    "bestFor": "Sunny window / balcony",
    "temperature": "18–32°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Cactus",
    "price": 500,
    "category": "Succulent",
    "description": "A drought-tolerant desert plant that needs strong light, gritty soil and infrequent watering.",
    "image": "https://images.pexels.com/photos/97260/pexels-photo-97260.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright direct",
    "water": "Every 2–4 weeks",
    "difficulty": "Very easy",
    "height": "6 in–3 ft",
    "bestFor": "Sunny window",
    "temperature": "18–35°C",
    "petSafety": "Spines; keep away from children/pets"
  },
  {
    "name": "Echeveria",
    "price": 550,
    "category": "Succulent",
    "description": "A compact rosette succulent with thick leaves. Keep it in bright light and use a fast-draining mix.",
    "image": "https://images.pexels.com/photos/37173483/pexels-photo-37173483.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright direct / filtered",
    "water": "Every 2–3 weeks",
    "difficulty": "Easy",
    "height": "4–8 in",
    "bestFor": "Sunny window",
    "temperature": "15–30°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Haworthia",
    "price": 600,
    "category": "Succulent",
    "description": "A small striped or patterned succulent that handles bright indirect light and needs less sun than many desert succulents.",
    "image": "https://images.pexels.com/photos/11216397/pexels-photo-11216397.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect",
    "water": "Every 2–3 weeks",
    "difficulty": "Very easy",
    "height": "4–8 in",
    "bestFor": "Desk / window",
    "temperature": "15–30°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Jade Plant",
    "price": 950,
    "category": "Succulent",
    "description": "A long-lived succulent with fleshy leaves and branching stems. Allow the potting mix to dry between waterings.",
    "image": "https://images.pexels.com/photos/8507297/pexels-photo-8507297.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright light",
    "water": "Every 2–3 weeks",
    "difficulty": "Easy",
    "height": "1–3 ft",
    "bestFor": "Sunny window",
    "temperature": "18–30°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "String of Pearls",
    "price": 750,
    "category": "Succulent",
    "description": "A trailing succulent with bead-like leaves. It needs strong indirect light and careful watering to avoid root rot.",
    "image": "https://images.pexels.com/photos/13799658/pexels-photo-13799658.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect",
    "water": "Every 2–3 weeks",
    "difficulty": "Medium",
    "height": "1–3 ft trailing",
    "bestFor": "Hanging pot",
    "temperature": "15–30°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Panda Plant",
    "price": 700,
    "category": "Succulent",
    "description": "A fuzzy-leaved succulent with attractive brown-edged leaves. It prefers bright light and dry conditions.",
    "image": "https://images.pexels.com/photos/813356/pexels-photo-813356.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright light",
    "water": "Every 2–3 weeks",
    "difficulty": "Easy",
    "height": "1–2 ft",
    "bestFor": "Sunny window",
    "temperature": "18–30°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Zebra Haworthia",
    "price": 650,
    "category": "Succulent",
    "description": "A small striped rosette succulent that is compact, attractive and beginner-friendly.",
    "image": "https://images.pexels.com/photos/20216923/pexels-photo-20216923.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect",
    "water": "Every 2–3 weeks",
    "difficulty": "Very easy",
    "height": "3–6 in",
    "bestFor": "Desk / window",
    "temperature": "15–30°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Gasteria",
    "price": 700,
    "category": "Succulent",
    "description": "A slow-growing succulent with thick tongue-shaped leaves. It tolerates indoor conditions and needs well-drained soil.",
    "image": "https://images.pexels.com/photos/18498139/pexels-photo-18498139.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect",
    "water": "Every 2–3 weeks",
    "difficulty": "Easy",
    "height": "6–12 in",
    "bestFor": "Desk / window",
    "temperature": "15–30°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Sedum Burrito",
    "price": 800,
    "category": "Succulent",
    "description": "A trailing succulent with plump bead-like leaves. Its stems look especially attractive in hanging planters.",
    "image": "https://images.pexels.com/photos/19369503/pexels-photo-19369503.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect",
    "water": "Every 2–3 weeks",
    "difficulty": "Medium",
    "height": "1–2 ft trailing",
    "bestFor": "Hanging pot",
    "temperature": "15–30°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Rose Plant",
    "price": 1000,
    "category": "Flower",
    "description": "A classic flowering plant with fragrant, colorful blooms. It needs plenty of sunlight, airflow and regular watering.",
    "image": "https://images.pexels.com/photos/4238358/pexels-photo-4238358.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "6+ hours of sunlight",
    "water": "Every 1–2 days in hot weather",
    "difficulty": "Medium",
    "height": "2–5 ft",
    "bestFor": "Balcony / garden",
    "temperature": "18–32°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Marigold",
    "price": 450,
    "category": "Flower",
    "description": "A cheerful flowering annual with yellow or orange blooms. It grows quickly with sunlight and well-drained soil.",
    "image": "https://images.pexels.com/photos/10824485/pexels-photo-10824485.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Full sun",
    "water": "Daily or when topsoil dries",
    "difficulty": "Easy",
    "height": "1–2 ft",
    "bestFor": "Balcony / garden",
    "temperature": "18–32°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Petunia",
    "price": 500,
    "category": "Flower",
    "description": "A colorful flowering plant that performs well in containers when given sunlight, regular watering and occasional feeding.",
    "image": "https://images.pexels.com/photos/15824924/pexels-photo-15824924.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Full sun",
    "water": "Daily in hot weather",
    "difficulty": "Easy",
    "height": "8–16 in",
    "bestFor": "Balcony / window box",
    "temperature": "18–32°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Geranium",
    "price": 650,
    "category": "Flower",
    "description": "A popular container flowering plant with long-lasting blooms. Avoid waterlogged soil and provide plenty of light.",
    "image": "https://images.pexels.com/photos/35127683/pexels-photo-35127683.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Full sun to bright light",
    "water": "Every 2–3 days",
    "difficulty": "Easy",
    "height": "1–2 ft",
    "bestFor": "Balcony / window",
    "temperature": "15–30°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Orchid",
    "price": 1400,
    "category": "Flower",
    "description": "An elegant flowering plant that prefers bright filtered light, good airflow and a specialized airy growing medium.",
    "image": "https://images.pexels.com/photos/5714450/pexels-photo-5714450.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect",
    "water": "About weekly",
    "difficulty": "Medium",
    "height": "1–2 ft",
    "bestFor": "Bright indoor space",
    "temperature": "18–30°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Anthurium",
    "price": 1250,
    "category": "Flower",
    "description": "A tropical flowering houseplant with glossy leaves and long-lasting colorful spathes. It enjoys warmth and humidity.",
    "image": "https://images.pexels.com/photos/3290584/pexels-photo-3290584.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect",
    "water": "Weekly",
    "difficulty": "Medium",
    "height": "1–2 ft",
    "bestFor": "Indoor / shaded balcony",
    "temperature": "18–30°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "Jasmine",
    "price": 900,
    "category": "Flower",
    "description": "A fragrant flowering climber that rewards sunlight and support for its twining stems.",
    "image": "https://images.pexels.com/photos/5741789/pexels-photo-5741789.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Full sun to partial sun",
    "water": "2–3 times weekly",
    "difficulty": "Medium",
    "height": "3–8 ft",
    "bestFor": "Balcony / garden",
    "temperature": "18–32°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Dahlia",
    "price": 850,
    "category": "Flower",
    "description": "A showy flowering plant with large blooms in many colors. It needs sunlight, rich soil and consistent moisture.",
    "image": "https://images.pexels.com/photos/8112801/pexels-photo-8112801.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Full sun",
    "water": "2–3 times weekly",
    "difficulty": "Medium",
    "height": "2–4 ft",
    "bestFor": "Garden / balcony",
    "temperature": "18–30°C",
    "petSafety": "Generally pet-safe"
  },
  {
    "name": "Chrysanthemum",
    "price": 700,
    "category": "Flower",
    "description": "A compact flowering plant with many colorful blooms. Bright light and regular deadheading help extend flowering.",
    "image": "https://images.pexels.com/photos/906156/pexels-photo-906156.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright light / morning sun",
    "water": "2–3 times weekly",
    "difficulty": "Medium",
    "height": "1–3 ft",
    "bestFor": "Balcony / patio",
    "temperature": "15–28°C",
    "petSafety": "Pet-toxic if chewed"
  },
  {
    "name": "African Violet",
    "price": 800,
    "category": "Flower",
    "description": "A compact indoor flowering plant with soft leaves and colorful blooms. Water at the soil level and avoid wetting the leaves.",
    "image": "https://images.pexels.com/photos/17067718/pexels-photo-17067718.jpeg?auto=compress&cs=tinysrgb&w=900",
    "light": "Bright indirect",
    "water": "About weekly",
    "difficulty": "Medium",
    "height": "4–8 in",
    "bestFor": "Desk / window",
    "temperature": "18–27°C",
    "petSafety": "Generally pet-safe"
  }
];

(async()=>{
  try{
    if(!process.env.MONGO_URI) throw new Error('MONGO_URI is missing in backend/.env');
    await mongoose.connect(process.env.MONGO_URI);
    await Plant.deleteMany({});
    await Plant.insertMany(plants);
    console.log(`GreenLeaf BD: ${plants.length} plants added successfully (10 per category).`);
  }catch(e){console.error('Seed failed:',e.message);}
  finally{await mongoose.disconnect();}
})();
